namespace ProyectoSaberProWeb.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<ProyectoSaberProWeb.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            ContextKey = "ProyectoSaberProWeb.Models.ApplicationDbContext";
        }

        protected override void Seed(ProyectoSaberProWeb.Models.ApplicationDbContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data.
            context.Roles.AddOrUpdate(x => x.Id,
                new Microsoft.AspNet.Identity.EntityFramework.IdentityRole { Id = "1", Name = "Administrador"},
                new Microsoft.AspNet.Identity.EntityFramework.IdentityRole { Id = "2", Name = "Docente" },
                new Microsoft.AspNet.Identity.EntityFramework.IdentityRole { Id = "3", Name = "Alumno" }
                );
            context.departamentos.AddOrUpdate(
                new Models.Departamento { ID = 11, Nombre = "Bogotá D.C." },
                new Models.Departamento { ID = 13, Nombre = "Bolívar"},
                new Models.Departamento { ID = 15, Nombre = "Boyacá"},
                new Models.Departamento { ID = 17, Nombre = "Caldas"},
                new Models.Departamento { ID = 18, Nombre = "Caquetá"},
                new Models.Departamento { ID = 19, Nombre = "Cauca"},
                new Models.Departamento { ID = 20, Nombre = "Cesar"},
                new Models.Departamento { ID = 23, Nombre = "Córdoba"},
                new Models.Departamento { ID = 25, Nombre = "Cundinamarca"},
                new Models.Departamento { ID = 27, Nombre = "Chocó"},
                new Models.Departamento { ID = 41, Nombre = "Huila"},
                new Models.Departamento { ID = 44, Nombre = "La Guajira"},
                new Models.Departamento { ID = 47, Nombre = "Magdalena"},
                new Models.Departamento { ID = 5,  Nombre = "Antioquia"},
                new Models.Departamento { ID = 50, Nombre = "Meta"},
                new Models.Departamento { ID = 52, Nombre = "Nariño"},
                new Models.Departamento { ID = 54, Nombre = "Norte de Santander"},
                new Models.Departamento { ID = 63, Nombre = "Quindío"},
                new Models.Departamento { ID = 66, Nombre = "Risaralda"},
                new Models.Departamento { ID = 68, Nombre = "Santander"},
                new Models.Departamento { ID = 70, Nombre = "Sucre"},
                new Models.Departamento { ID = 73, Nombre = "Tolima"},
                new Models.Departamento { ID = 76, Nombre = "Valle del Cauca"},
                new Models.Departamento { ID = 8,  Nombre = "Atlántico"},
                new Models.Departamento { ID = 81, Nombre = "Arauca"},
                new Models.Departamento { ID = 85, Nombre = "Casanare"},
                new Models.Departamento { ID = 86, Nombre = "Putumayo"},
                new Models.Departamento { ID = 88, Nombre = "Archipiélago de San Andrés, Providencia y Santa Catalina"},
                new Models.Departamento { ID = 91, Nombre = "Amazonas"},
                new Models.Departamento { ID = 94, Nombre = "Guainía"},
                new Models.Departamento { ID = 95, Nombre = "Guaviare"},
                new Models.Departamento { ID = 97, Nombre = "Vaupés"},
                new Models.Departamento { ID = 99, Nombre = "Vichada"}
                );
            context.ciudades.AddOrUpdate(
                new Models.Ciudad { Departamento_Id = 5,  ID = 5001,  Nombre = "Medellín" },
                new Models.Ciudad { Departamento_Id = 5,  ID = 5002,  Nombre = "Abejorral" },
                new Models.Ciudad { Departamento_Id = 70, ID = 70670, Nombre = "Sampués" },
                new Models.Ciudad { Departamento_Id = 85, ID = 85225, Nombre = "Nunchía" },
                new Models.Ciudad { Departamento_Id = 54, ID = 54518, Nombre = "Pamplona" },
                new Models.Ciudad { Departamento_Id = 25, ID = 25019, Nombre = "Albán" },
                new Models.Ciudad { Departamento_Id = 97, ID = 97889, Nombre = "Yavaraté" },
                new Models.Ciudad { Departamento_Id = 23, ID = 23466, Nombre = "Montelíbano" },
                new Models.Ciudad { Departamento_Id = 86, ID = 86568, Nombre = "Puerto Asís" },
                new Models.Ciudad { Departamento_Id = 70, ID = 70215, Nombre = "Corozal" },
                new Models.Ciudad { Departamento_Id = 52, ID = 52110, Nombre = "Buesaco" },
                new Models.Ciudad { Departamento_Id = 85, ID = 85139, Nombre = "Maní" },
                new Models.Ciudad { Departamento_Id = 8,  ID = 8001,  Nombre = "Barranquilla" },
                new Models.Ciudad { Departamento_Id = 8,  ID = 8078,  Nombre = "Baranoa" },
                new Models.Ciudad { Departamento_Id = 13, ID = 13268, Nombre = "El Peñón" },
                new Models.Ciudad { Departamento_Id = 8,  ID = 8141,  Nombre = "Candelaria" },
                new Models.Ciudad { Departamento_Id = 8,  ID = 8296,  Nombre = "Galapa" },
                new Models.Ciudad { Departamento_Id = 76, ID = 76834, Nombre = "Tuluá" },
                new Models.Ciudad { Departamento_Id = 73, ID = 73152, Nombre = "Casabianca" },
                new Models.Ciudad { Departamento_Id = 25, ID = 25040, Nombre = "Anolaima" },
                new Models.Ciudad { Departamento_Id = 8,  ID = 8549,  Nombre = "Piojó" },
                new Models.Ciudad { Departamento_Id = 8,  ID = 8558,  Nombre = "Polonuevo" },
                new Models.Ciudad { Departamento_Id = 25, ID = 25175, Nombre = "Chía" },
                new Models.Ciudad { Departamento_Id = 52, ID = 52835, Nombre = "San Andrés de Tumaco" },
                new Models.Ciudad { Departamento_Id = 18, ID = 18205, Nombre = "Curillo" },
                new Models.Ciudad { Departamento_Id = 18, ID = 18247, Nombre = "El Doncello" },
                new Models.Ciudad { Departamento_Id = 20, ID = 20517, Nombre = "Pailitas" },
                new Models.Ciudad { Departamento_Id = 27, ID = 27001, Nombre = "Quibdó" },
                new Models.Ciudad { Departamento_Id = 27, ID = 27006, Nombre = "Acandí" },
                new Models.Ciudad { Departamento_Id = 47, ID = 47189, Nombre = "Ciénaga" },
                new Models.Ciudad { Departamento_Id = 8,  ID = 8560,  Nombre = "Ponedera" },
                new Models.Ciudad { Departamento_Id = 50, ID = 50686, Nombre = "San Juanito" },
                new Models.Ciudad { Departamento_Id = 50, ID = 50689, Nombre = "San Martín" },
                new Models.Ciudad { Departamento_Id = 15, ID = 15832, Nombre = "Tununguá" },
                new Models.Ciudad { Departamento_Id = 52, ID = 52079, Nombre = "Barbacoas" },
                new Models.Ciudad { Departamento_Id = 15, ID = 15476, Nombre = "Motavita" },
                new Models.Ciudad { Departamento_Id = 52, ID = 52696, Nombre = "Santa Bárbara" },
                new Models.Ciudad { Departamento_Id = 68, ID = 68575, Nombre = "Puerto Wilches" },
                new Models.Ciudad { Departamento_Id = 68, ID = 68573, Nombre = "Puerto Parra" },
                new Models.Ciudad { Departamento_Id = 63, ID = 63001, Nombre = "Armenia" },
                new Models.Ciudad { Departamento_Id = 63, ID = 63111, Nombre = "Buenavista" },
                new Models.Ciudad { Departamento_Id = 18, ID = 18610, Nombre = "San José del Fragua" },
                new Models.Ciudad { Departamento_Id = 50, ID = 50110, Nombre = "Barranca de Upía" },
                new Models.Ciudad { Departamento_Id = 25, ID = 25662, Nombre = "San Juan de Río Seco" },
                new Models.Ciudad { Departamento_Id = 8,  ID = 8372,  Nombre = "Juan de Acosta" },
                new Models.Ciudad { Departamento_Id = 50, ID = 50287, Nombre = "Fuente de Oro" },
                new Models.Ciudad { Departamento_Id = 85, ID = 85325, Nombre = "San Luis de Gaceno" },
                new Models.Ciudad { Departamento_Id = 27, ID = 27250, Nombre = "El Litoral del San Juan" },
                new Models.Ciudad { Departamento_Id = 25, ID = 25843, Nombre = "Villa de San Diego de Ubate" },
                new Models.Ciudad { Departamento_Id = 13, ID = 13074, Nombre = "Barranco de Loba" },
                new Models.Ciudad { Departamento_Id = 15, ID = 15816, Nombre = "Togüí" },
                new Models.Ciudad { Departamento_Id = 13, ID = 13688, Nombre = "Santa Rosa del Sur" },
                new Models.Ciudad { Departamento_Id = 27, ID = 27135, Nombre = "El Cantón del San Pablo" },
                new Models.Ciudad { Departamento_Id = 15, ID = 15407, Nombre = "Villa de Leyva" },
                new Models.Ciudad { Departamento_Id = 47, ID = 47692, Nombre = "San Sebastián de Buenavista" },
                new Models.Ciudad { Departamento_Id = 15, ID = 15537, Nombre = "Paz de Río" },
                new Models.Ciudad { Departamento_Id = 13, ID = 13300, Nombre = "Hatillo de Loba" },
                new Models.Ciudad { Departamento_Id = 47, ID = 47660, Nombre = "Sabanas de San Angel" },
                new Models.Ciudad { Departamento_Id = 95, ID = 95015, Nombre = "Calamar" },
                new Models.Ciudad { Departamento_Id = 20, ID = 20614, Nombre = "Río de Oro" },
                new Models.Ciudad { Departamento_Id = 5,  ID = 5665,  Nombre = "San Pedro de Uraba" },
                new Models.Ciudad { Departamento_Id = 95, ID = 95001, Nombre = "San José del Guaviare" },
                new Models.Ciudad { Departamento_Id = 15, ID = 15693, Nombre = "Santa Rosa de Viterbo" },
                new Models.Ciudad { Departamento_Id = 19, ID = 19698, Nombre = "Santander de Quilichao" },
                new Models.Ciudad { Departamento_Id = 95, ID = 95200, Nombre = "Miraflores" },
                new Models.Ciudad { Departamento_Id = 5,  ID = 5042,  Nombre = "Santafé de Antioquia" },
                new Models.Ciudad { Departamento_Id = 50, ID = 50680, Nombre = "San Carlos de Guaroa" },
                new Models.Ciudad { Departamento_Id = 8,  ID = 8520,  Nombre = "Palmar de Varela" },
                new Models.Ciudad { Departamento_Id = 5,  ID = 5686,  Nombre = "Santa Rosa de Osos" },
                new Models.Ciudad { Departamento_Id = 5,  ID = 5647,  Nombre = "San Andrés de Cuerquía" },
                new Models.Ciudad { Departamento_Id = 73, ID = 73854, Nombre = "Valle de San Juan" },
                new Models.Ciudad { Departamento_Id = 68, ID = 68689, Nombre = "San Vicente de Chucurí" },
                new Models.Ciudad { Departamento_Id = 68, ID = 68684, Nombre = "San José de Miranda" },
                new Models.Ciudad { Departamento_Id = 88, ID = 88564, Nombre = "Providencia" },
                new Models.Ciudad { Departamento_Id = 73, ID = 73148, Nombre = "Carmen de Apicala" },
                new Models.Ciudad { Departamento_Id = 25, ID = 25645, Nombre = "San Antonio del Tequendama" },
                new Models.Ciudad { Departamento_Id = 68, ID = 68655, Nombre = "Sabana de Torres" },
                new Models.Ciudad { Departamento_Id = 95, ID = 95025, Nombre = "El Retorno" },
                new Models.Ciudad { Departamento_Id = 23, ID = 23682, Nombre = "San José de Uré" },
                new Models.Ciudad { Departamento_Id = 52, ID = 52694, Nombre = "San Pedro de Cartago" },
                new Models.Ciudad { Departamento_Id = 8,  ID = 8137,  Nombre = "Campo de La Cruz" },
                new Models.Ciudad { Departamento_Id = 50, ID = 50683, Nombre = "San Juan de Arama" },
                new Models.Ciudad { Departamento_Id = 5,  ID = 5658,  Nombre = "San José de La Montaña" },
                new Models.Ciudad { Departamento_Id = 18, ID = 18150, Nombre = "Cartagena del Chairá" },
                new Models.Ciudad { Departamento_Id = 27, ID = 27660, Nombre = "San José del Palmar" },
                new Models.Ciudad { Departamento_Id = 25, ID = 25001, Nombre = "Agua de Dios" },
                new Models.Ciudad { Departamento_Id = 13, ID = 13655, Nombre = "San Jacinto del Cauca" },
                new Models.Ciudad { Departamento_Id = 41, ID = 41668, Nombre = "San Agustín" },
                new Models.Ciudad { Departamento_Id = 52, ID = 52258, Nombre = "El Tablón de Gómez" },
                new Models.Ciudad { Departamento_Id = 88, ID = 88001, Nombre = "San Andrés" },
                new Models.Ciudad { Departamento_Id = 15, ID = 15664, Nombre = "San José de Pare" },
                new Models.Ciudad { Departamento_Id = 86, ID = 86865, Nombre = "Valle de Guamez" },
                new Models.Ciudad { Departamento_Id = 13, ID = 13670, Nombre = "San Pablo de Borbur" },
                new Models.Ciudad { Departamento_Id = 70, ID = 70820, Nombre = "Santiago de Tolú" },
                new Models.Ciudad { Departamento_Id = 11, ID = 11001, Nombre = "Bogotá D.C." },
                new Models.Ciudad { Departamento_Id = 44, ID = 44650, Nombre = "San Juan del Cesar" },
                new Models.Ciudad { Departamento_Id = 27, ID = 27086, Nombre = "Belén de Bajira" },
                new Models.Ciudad { Departamento_Id = 73, ID = 73678, Nombre = "San Luis" },
                new Models.Ciudad { Departamento_Id = 15, ID = 15676, Nombre = "San Miguel de Sema" },
                new Models.Ciudad { Departamento_Id = 73, ID = 73675, Nombre = "San Antonio" },
                new Models.Ciudad { Departamento_Id = 68, ID = 68673, Nombre = "San Benito" },
                new Models.Ciudad { Departamento_Id = 25, ID = 25862, Nombre = "Vergara" },
                new Models.Ciudad { Departamento_Id = 23, ID = 23678, Nombre = "San Carlos" },
                new Models.Ciudad { Departamento_Id = 91, ID = 91530, Nombre = "Puerto Alegría" },
                new Models.Ciudad { Departamento_Id = 68, ID = 68344, Nombre = "Hato" },
                new Models.Ciudad { Departamento_Id = 13, ID = 13654, Nombre = "San Jacinto" },
                new Models.Ciudad { Departamento_Id = 19, ID = 19693, Nombre = "San Sebastián" },
                new Models.Ciudad { Departamento_Id = 54, ID = 54344, Nombre = "Hacarí" },
                new Models.Ciudad { Departamento_Id = 54, ID = 54239, Nombre = "Durania" },
                new Models.Ciudad { Departamento_Id = 76, ID = 76828, Nombre = "Trujillo" },
                new Models.Ciudad { Departamento_Id = 76, ID = 76869, Nombre = "Vijes" }
                );
        }
    }
}
